spring:
  application.name: spring_templates
  datasource:
    url: jdbc:mariadb://localhost:3306/lora
    username: root
    password: 7590sa12
    driver-class-name: org.mariadb.jdbc.Driver

#    spring:
#      web:
#        resources:
#          add-mappings: true


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    username: ${ELASTIC_USERNAME:elastic}
    password: ${ELASTIC_PASSWORD:lAiO34cN}
    uris: ${ELASTIC_URI:localhost:9200}
server:
  shutdown: graceful

app:
  jwt:
    secret: 600644a6c4c8803e0218a3d0f078eae9d6a8071d3889ee302c99ba2cec91afc92015a39f2c1ad1201eccd12e60ecba2e9b17f885b04ef3f2137d01edd5f07c7a
    access_expires_after: 86400000
    refresh_expires_after: 172800000
    issuer: jombi
  elasticsearch:
    is-ssl: ${ELASTIC_CERT_ENABLED:false}
    certificate: ${ELASTIC_CERT_PATH:}
    cert-password: ${ELASTIC_CERT_PASSWORD:}

springdoc:
  api-docs:
    enabled: true
  enable-kotlin: true
  enable-javadoc: true
  swagger-ui:
    enabled: true
  trim-kotlin-indent: true
  use-fqn: true