spring:
  application.name: spring_templates
  datasource:
    url: jdbc:mariadb://${DATASOURCE_URL}/${DATASOURCE_PATH}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  shutdown: graceful

app:
  jwt:
    secret: ${JWT_SECRET}
    access_expires_after: 86400000
    refresh_expires_after: 172800000
    issuer: jombi
