spring:
  application.name: spring_templates
  datasource:
    url: jdbc:mariadb://${DATASOURCE_URL}/${DATASOURCE_PATH}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    username: ${ELASTIC_USERNAME:elastic}
    password: ${ELASTIC_PASSWORD}
    uris: ${ELASTIC_URI:http://localhost:9200}
server:
  shutdown: graceful

app:
  jwt:
    secret: ${JWT_SECRET}
    access_expires_after: 86400000
    refresh_expires_after: 172800000
    issuer: jombi

springdoc:
  api-docs:
    enabled: true
  enable-kotlin: true
  enable-javadoc: true
  swagger-ui:
    enabled: true
  trim-kotlin-indent: true
  use-fqn: true